server:
  port: 8888
spring:
  servlet:
    multipart:
      file-size-threshold: 0MB
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    include: dubbo
  #数据源
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/wechat_app_server?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: wangsr
    password: sssssss#
    hikari:
      connection-timeout: 60000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 60000
      max-lifetime: 180000

  mail:
    host: smtp.exmail.qq.com
    username: suc@wangsrbus.cn
    password: sssssssssssss
    nickname: 苏克社区
    port: 465
    properties:
      mail.smtp.auth: true
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false
  # redis配置，以下有默认配置的也可以使用默认配置
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password: sss


# mybatis plus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml,classpath:mapper/ext/*.xml
  type-aliases-package: cn.wangsr.model.po
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0

# 阿里oss
oss:
  endpoint: oss-cn-beijing.aliyuncs.com
  accessKeyId: LTAI4weweucaKeUw7Np
  accessKeySecret: H4CkvsssssssStOfFuNzcrEN
  bucketName: wangsr-oss-files
  folder: images/

##wx小程序
wx:
  appId: 23243545
  secret: 5676766666666666666

